"""The Hodge decomposition without building the curl operator.

Why this exists
---------------
``topology.hodge_decomposition`` builds ``d1`` as a dense ``(T, E)`` array and
solves two least squares problems against it. On the A2 graphs that is the right
thing: the matrix is small, the code says exactly what the arithmetic is, and
nothing is hidden behind an iteration count.

It stops being the right thing when the graph comes from outside the model. A
near-complete graph on a few dozen nodes already has tens of thousands of
triangles, and ``d1`` at ``(15136, 1034)`` is 125 MB for one date; a graph with
four hundred nodes puts it past what a machine will hold. The arithmetic is not
the problem. **Materialising an operator whose every row has three non-zeros is
the problem.**

This module solves the same least squares problem by CGLS, applying ``d1`` and
``d1.T`` through the triangle list rather than through a matrix. Nothing else
changes: same faces, same orthogonal split, same three components.

    gradient  : the part a scalar node potential accounts for
    curl      : the part generated by loop sums around filled triangles
    harmonic  : what is left, orthogonal to both

Which one to call
-----------------
``topology.hodge_decomposition`` is the reference and stays the reference. Use
this one where that one will not fit in memory, and **check them against each
other on a case where both run**, which is what ``selftest`` does.

No new dependency: CGLS is twenty lines of numpy, and ``requirements.txt`` pins
what it pins for a reason.

A reading that costs nothing and is worth printing
--------------------------------------------------
The dimension of the harmonic space is ``E - rank(d0) - rank(d1)``, and it is
**zero on every published input-output table tested so far**. That is a statement
about triangles filling the cycle space, not about the flow: the non-gradient
part on those same carriers is 82 to 96 per cent of the energy, and all of it
sits in ``curl``. **A zero harmonic dimension is not an absence of circulation.**

``rank(d0) == V - C`` is a free self-check on any graph and is worth asserting
wherever the dimension is computed: it caught one implementation error where a
reduced QR on a wide matrix returned a full square ``Q``, projecting away the
whole space and reading the dimension as zero when it was five.
"""

from __future__ import annotations

import numpy as np

from .topology import (
    incidence_matrix,
    net_flow_vector,
    triangles,
    undirected_edges,
)

__all__ = ["hodge_cgls", "harmonic_dimension"]


def _triangle_index(adjacency: np.ndarray):
    """Flat ``(edge, triangle, sign)`` triples standing in for ``d1``.

    Orientation is ``topology.curl_matrix``'s and is not restated as a choice:
    for a triangle ``i < j < k`` the signs are ``+1`` on ``(i, j)``, ``+1`` on
    ``(j, k)`` and ``-1`` on ``(i, k)``. A second convention here would be a
    second truth about what a loop sum means.
    """
    edges = undirected_edges(adjacency)
    at = {(int(i), int(j)): e for e, (i, j) in enumerate(edges)}
    tris = triangles(adjacency)
    n = len(tris)
    ei = np.empty(3 * n, dtype=np.int64)
    ti = np.empty(3 * n, dtype=np.int64)
    sg = np.empty(3 * n)
    for t, (i, j, k) in enumerate(tris):
        for o, (a, b, s) in enumerate(((i, j, 1.0), (j, k, 1.0), (i, k, -1.0))):
            ei[3 * t + o] = at[(int(a), int(b))]
            ti[3 * t + o] = t
            sg[3 * t + o] = s
    return len(edges), n, ei, ti, sg


def hodge_cgls(flow: np.ndarray, adjacency: np.ndarray, *,
               tol: float = 1e-13, iter_lim: int = 5000):
    """``(gradient, curl, harmonic, n_triangles, iterations)``.

    Equivalent to ``topology.hodge_decomposition(..., fill_triangles=True)``.
    The gradient step stays dense: ``d0`` is ``(E, V)`` and V is small.
    """
    w = net_flow_vector(flow, adjacency)
    d0 = incidence_matrix(adjacency)
    potential, *_ = np.linalg.lstsq(d0, w, rcond=None)
    grad = d0 @ potential
    residual = w - grad

    m, n_tri, ei, ti, sg = _triangle_index(adjacency)
    if n_tri == 0:
        return grad, np.zeros_like(w), residual, 0, 0

    def apply(c):                       # d1.T @ c
        return np.bincount(ei, weights=sg * c[ti], minlength=m)

    def apply_t(r):                     # d1 @ r
        return np.bincount(ti, weights=sg * r[ei], minlength=n_tri)

    x = np.zeros(n_tri)
    r = residual.copy()
    s = apply_t(r)
    p = s.copy()
    gamma = float(s @ s)
    gamma0 = gamma
    it = 0
    for it in range(1, iter_lim + 1):
        q = apply(p)
        qq = float(q @ q)
        if qq == 0.0:
            break
        alpha = gamma / qq
        x += alpha * p
        r -= alpha * q
        s = apply_t(r)
        gamma_new = float(s @ s)
        if gamma_new <= tol * tol * gamma0:
            break
        p = s + (gamma_new / gamma) * p
        gamma = gamma_new

    curl = apply(x)
    return grad, curl, residual - curl, n_tri, it


def harmonic_dimension(adjacency: np.ndarray, *, tol: float = 1e-9) -> int:
    """``E - rank(d0) - rank(d1)``, with the free self-check on ``rank(d0)``.

    ``rank(d1)`` is taken from the Gram matrix ``d1.T @ d1``, which is ``(E, E)``
    and is built from the triangle list, so the ``(T, E)`` operator is never
    materialised. Cheap sufficient condition before paying for this at all:
    ``len(triangles) < E - V + C`` forces a positive dimension, because
    ``rank(d1) <= len(triangles)``.
    """
    from .topology import connected_components

    v = adjacency.shape[0]
    e = len(undirected_edges(adjacency))
    c = connected_components(adjacency)

    d0 = incidence_matrix(adjacency)
    s0 = np.linalg.svd(d0, compute_uv=False)
    r0 = int((s0 > tol * s0[0]).sum()) if s0.size else 0
    if r0 != v - c:
        raise AssertionError(f"rank(d0) is {r0}, not V - C = {v - c}")

    m, n_tri, ei, ti, sg = _triangle_index(adjacency)
    if n_tri == 0:
        return e - r0

    gram = np.zeros((m, m))
    edge = ei.reshape(n_tri, 3)
    sign = sg.reshape(n_tri, 3)
    for a in range(3):
        for b in range(3):
            np.add.at(gram, (edge[:, a], edge[:, b]), sign[:, a] * sign[:, b])
    return e - r0 - int(np.linalg.matrix_rank(gram))
